services:
  - type: web
    name: linkedin-automation
    runtime: python
    pythonVersion: "3.9"
    buildCommand: |
      # Print initial system info
      echo "Starting build process..."
      pwd
      ls -la
      
      # Create necessary directories with explicit permissions
      sudo mkdir -p /usr/local/bin
      sudo mkdir -p /tmp
      sudo chmod 777 /tmp
      sudo chmod 777 /usr/local/bin
      
      # Update package repositories
      sudo apt-get update
      sudo apt-get install -y wget unzip gnupg2 apt-transport-https ca-certificates
      
      # Install Chromium and ChromeDriver
      sudo apt-get install -y chromium-browser chromium-chromedriver
      
      # Create explicit symlinks with sudo
      sudo ln -sf /usr/bin/chromium-browser /usr/bin/google-chrome-stable
      sudo ln -sf /usr/bin/chromium-browser /usr/local/bin/google-chrome
      
      # Set Chrome binary location
      export CHROME_BIN=/usr/bin/chromium-browser
      
      # Explicitly set ChromeDriver symlink and permissions
      sudo ln -sf /usr/bin/chromedriver /usr/local/bin/chromedriver
      sudo chmod +x /usr/local/bin/chromedriver
      
      # Verify installations
      echo "Verifying installations:"
      $CHROME_BIN --version || true
      /usr/local/bin/chromedriver --version || true
      ls -la /usr/local/bin/chromedriver
      
      # Install Python dependencies
      pip install -r requirements.txt
      
      # Final system check with full paths
      echo "Final system check:"
      /usr/bin/chromium-browser --version
      /usr/local/bin/chromedriver --version
      
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: CHROME_BINARY_LOCATION
        value: /usr/bin/chromium-browser
      - key: CHROMEDRIVER_PATH
        value: /usr/local/bin/chromedriver
      - key: PATH
        value: /usr/local/bin:/usr/bin:${PATH}