services:
  - type: web
    name: linkedin-automation
    runtime: python
    pythonVersion: "3.9"
    buildCommand: |
      # Update package list and install prerequisites
      apt-get update
      apt-get install -y wget unzip gnupg curl apt-transport-https ca-certificates

      # Set up Chrome repository properly
      wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
      echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list
      apt-get update

      # Install Chrome with explicit version pinning
      apt-get install -y google-chrome-stable=120.0.6099.* || apt-get install -y google-chrome-stable

      # Verify Chrome installation
      google-chrome-stable --version

      # Install matching chromedriver
      CHROME_VERSION=$(google-chrome-stable --version | awk '{print $3}' | cut -d. -f1)
      CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION}")
      wget -q "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
      unzip -q chromedriver_linux64.zip
      mv chromedriver /usr/local/bin/
      chmod +x /usr/local/bin/chromedriver
      rm chromedriver_linux64.zip

      # Set up directories and permissions
      mkdir -p /tmp
      chmod 777 /tmp
      chmod 755 /usr/local/bin/chromedriver
      chmod 755 /usr/bin/google-chrome-stable

      # Verify installations
      echo "Chrome version:"
      google-chrome-stable --version
      echo "Chrome location:"
      which google-chrome-stable
      echo "Chromedriver version:"
      chromedriver --version
      echo "Chromedriver location:"
      which chromedriver

      # Install Python dependencies
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: PYTHONUNBUFFERED
        value: true
      - key: CHROME_BIN  # Add explicit Chrome binary location
        value: /usr/bin/google-chrome-stable
      - key: CHROMEDRIVER_PATH  # Add explicit chromedriver location
        value: /usr/local/bin/chromedriver
    healthCheckPath: /
    buildFilter:
      paths:
        - requirements.txt
        - app.py
        - templates/**
        - static/**