services:
  - type: web
    name: linkedin-automation
    runtime: python
    pythonVersion: "3.9"
    buildCommand: |
      apt-get update && apt-get install -y wget unzip gnupg
      wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | gpg --dearmor -o /usr/share/keyrings/google-chrome-keyring.gpg
      echo "deb [arch=amd64 signed-by=/usr/share/keyrings/google-chrome-keyring.gpg] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list
      apt-get update && apt-get install -y google-chrome-stable
      CHROME_VERSION=$(google-chrome --version | awk '{print $3}')
      wget https://chromedriver.storage.googleapis.com/${CHROME_VERSION}/chromedriver_linux64.zip
      unzip chromedriver_linux64.zip
      mv chromedriver /usr/local/bin/
      rm chromedriver_linux64.zip
      pip install -r requirements.txt
    startCommand: gunicorn app:app